---
name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x]
    name: Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.node-version }}
        uses: actions/checkout@v3

      - name: Setup and Test ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install node modules
        shell: bash
        run: yarn

      - name: Build
        shell: bash
        run: yarn build

      - name: Unit testing and collect coverage
        shell: bash
        run: yarn test